---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: stackrox
  name: init-bundle
  annotations:
        argocd.argoproj.io/sync-wave: "2"   
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: init-bundle-edit
  namespace: stackrox
  annotations:
        argocd.argoproj.io/sync-wave: "3"   
subjects:
  - kind: ServiceAccount
    name: init-bundle
    namespace: stackrox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
