apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync  
  name: openshift-advanced-cluster-mgmt
  namespace: openshift-advanced-cluster-mgmt
spec:
  targetNamespaces:
  - openshift-advanced-cluster-mgmt