apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: multiclusterhub
  namespace: openshift-advanced-cluster-mgmt
spec:
  imagePullSecret: acm-pullsecret