apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shellshock
    team: test-team
  annotations:
    argocd.argoproj.io/sync-wave: "4"      
  name: shell
  namespace: stackrox-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellshock
      deployment: shell
      team: test-team
  strategy: {}
  template:
    metadata:
      labels:
        app: shellshock
        deployment: shell
        team: test-team
    spec:
      containers:
      - image: 'vulnerables/cve-2014-6271'
        name: shell
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      serviceAccount: default
