apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rce
  name: samba
  namespace: stackrox-sample-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
      deployment: samba
  strategy: {}
  template:
    metadata:
      labels:
        app: samba
        deployment: samba
    spec:
      containers:
      - image: 'vulnerables/cve-2017-7494'
        name: samba
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      serviceAccount: default
