apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/giofontana/argocd-ocp.git'
    path: quay/operators
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=false
