apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackrox
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/giofontana/argocd-ocp.git'
    path: acs/unified
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
